version: '3'
services: 
  emailserver:
    build: Email-Server/
    depends_on: 
      - database

    ports:
      - '3001:3001'

    command: node app.js


  database:
    image: postgres:latest
    restart: always
    ports:
     - '5432:5432'
  
    environment: 
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: emails

    
    command: "docker run --name postgres -e POSTGRES_PASSWORD=pass -d postgres &&createdb emaildb"
